# @package _group_

mlflow_runname: pretraining

train_parameters:
  lr: 0.03
  batch_size: 256
  seed: 9999
  start_epoch: 0
  n_epoch: 1200
  dim: 2048
  pred_dim: 512
  fix_pred_lr: false

moco:
  dim: 128
  queue: 65536
  momentum: 0.999
  temperature: 0.07
  mlp: false
  cosine: true


dataset: CIFAR10

hydra:
  run:
    dir: logs/${mlflow_runname}/${dataset}/${train_parameters.seed}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${mlflow_runname}/${dataset}/${train_parameters.seed}
    subdir: ${now:%Y-%m-%d_%H-%M-%S}